title: Rajat Kumar
logo: /assets/img/GithubPortfolioPic.JPG
description: 
  <p align="center">
  <a href="https://www.linkedin.com/in/rajat-kumar-27506062/">LinkedIn</a> |
  <a href="https://github.com/allenpaine">GitHub</a>
  
  <br>   
  I'm currently pursuing an Executive PG Programme in ML & AI
  <br>
  </p>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
